name: PR check

on:
  pull_request:

concurrency: ${{ github.ref }}

jobs:
  main:
    name: Build & test the code
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        name: Setup dotnet 10.0.x
        with:
          dotnet-version: 10.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build the code
        run: dotnet build --no-restore

      - name: Test the code
        run: dotnet test --no-build --coverage --coverage-output-format cobertura --coverage-output cobertura.coverage.xml --report-xunit-trx

      - name: Comment unit test results
        uses: bibipkins/dotnet-test-reporter@v1.6.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Unit Test Results'
          results-path: "**/TestResults/*.trx"
          coverage-path: "**/TestResults/*.coverage.xml"
          coverage-type: 'cobertura'
          coverage-threshold: 50
          allow-failed-tests: true
          pull-request-check: true
